<a href="https://colab.research.google.com/github/nithin-k-mundrathi/python_practice/blob/main/Python_New_Programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
s = "India"
print(s[::-1],len(s))

aidnI 5


In [ ]:
# increment a character
s= 'N'
print(chr(ord(s) +1), bytes(s, 'utf-8'))

O b'N'


In [ ]:
# Count the number of Digits
import numpy as np
N = 1000
np.log10(100) +1

3.0

In [ ]:
# Reverse a Number



In [ ]:
import sys
-sys.maxsize -1

-9223372036854775808

In [ ]:
a = [1,75,6,2,3]

In [ ]:
round(1.1234,1),round(1.1234,2),round(1.1234,3)

(1.1, 1.12, 1.123)

### MAx Continous Sub Array of of length =k

In [ ]:
int_min = -sys.maxsize-1

for i in range(len(a)-2-1):
  max_sum = 0
  for j in range(2):
    max_sum = max_sum + a[i+j]

  int_min = max(int_min,max_sum)

In [ ]:
int_min

81

### PRime _Number


In [ ]:
n = 21
for i in range(2,int(n/2)+1):
  if n%i==0:
    print(False)
    break
  else:
    print(True)

True
False


In [ ]:
def prime_N(n):

  for i in range(n):

    for j in range(2, int(i/2)+1):
      if i%j==0:
        break
      print(i)

### GCD


In [ ]:
def gcd(a,b):
  if b==0:
    return a
  else:
    return gcd(b,a%b)

In [ ]:
gcd(16,4)

4

In [ ]:
a = [1,2,3,4,5]
b = [5,2,7,9]

list(set(a) & set(b))

[2, 5]

  ### Join all elements in a list

In [ ]:
    n = int(input())
    k = ''.join([str(i) for i in range(1,n+1)])
    print(k)

5
12345


In [ ]:
arr  = list(map(int, input().split()))
k=-1000
print(arr)
for i in arr:
    if i >= k:
        k=i
print(k)
z = []
for p in arr:
    if p !=k:
        z.append(p)

print(max(z))

6 6 6 6 6 6 6 6 6 5
[6, 6, 6, 6, 6, 6, 6, 6, 6, 5]
6
5


### Second largest

In [ ]:
n1 =n2 =1000000

for i in list_scores:

    if i < n1:
        n2 = n1
        n1 = i

    elif i<n2 and i!=n1:
        n2 = i
a = []
for j in list_o:
    if j[1] == n2:
        a.append(j[0])

List comprehensions


In [ ]:
x,y,z = map(int,input().split())
list_1 = [i for i in range(x+1)]
list_2 = [i for i in range(y+1)]
list_3 = [i for i in range(z+1)]
p = [[i,j,k] for i in list_1 for j in list_2 for k in list_3 if i+j+k !=n]

print(p)

2 3 4
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 0, 3], [0, 0, 4], [0, 1, 0], [0, 1, 1], [0, 1, 2], [0, 1, 3], [0, 2, 0], [0, 2, 1], [0, 2, 2], [0, 2, 4], [0, 3, 0], [0, 3, 1], [0, 3, 3], [0, 3, 4], [1, 0, 0], [1, 0, 1], [1, 0, 2], [1, 0, 3], [1, 1, 0], [1, 1, 1], [1, 1, 2], [1, 1, 4], [1, 2, 0], [1, 2, 1], [1, 2, 3], [1, 2, 4], [1, 3, 0], [1, 3, 2], [1, 3, 3], [1, 3, 4], [2, 0, 0], [2, 0, 1], [2, 0, 2], [2, 0, 4], [2, 1, 0], [2, 1, 1], [2, 1, 3], [2, 1, 4], [2, 2, 0], [2, 2, 2], [2, 2, 3], [2, 2, 4], [2, 3, 1], [2, 3, 2], [2, 3, 3], [2, 3, 4]]


List comprehension with if and else

In [ ]:
def swap_case(s):
    list_s = s.split(' ')
    k =[]
    for i in list_s:
        # if else comes first in list comprehension
        k.append(''.join(
            [j.lower() if j.isupper() else j.upper() for j in list(i)]))
    return ' '.join(k)

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

Avg using a Dict upto 2 decimal places

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

    print(
        '{:.2f}'.format(sum(student_marks[query_name][:])/len(student_marks[query_name]))
        )

  # give : when formatting to decide as number and just {} as a string
  output = "Hello {.3f} {}! You just delved into python.".format(10,last)
  print(output)

In [ ]:
print('{:.4f}'.format(7)),print('{:.4f}'.format(70)),print('{:.4f}'.format(10))

7.0000
70.0000
10.0000


(None, None, None)

In [ ]:
list_1 = [1,23,4]

list_1[2] = list_1[2] - 1
list_1

[1, 23, 3]

Lists

In [ ]:
if __name__ == '__main__':
    N = int(input())
    list_1 = []
    for i in range(N):
        a  = input().split()
        if a[0]=='insert':
            list_1.insert(int(a[1]),int(a[2]))
        if a[0]=='print':
            print(list_1)
        if a[0] == 'remove':
            list_1.remove(int(a[1]))
        if a[0] == 'append':
            list_1.append(int(a[1]))
        if a[0] == 'pop':
            list_1.pop()
        if a[0] == 'reverse':
            list_1.reverse()
        if a[0] == 'sort':
            list_1.sort()


In [ ]:
pos = [1,2,3,4]
pos[::-1]

[4, 3, 2, 1]

Numpy


In [ ]:
import numpy as np
np.set_printoptions(legacy = '1.13')
a,b  = tuple(map(int,input().split()))
print(a,b)
# print(np.identity(a))
print(np.eye(a,b,k=0))
print(np.empty(shape=(a,b)))
arr_a= np.empty((a,b))
print(arr_a)

3 3
3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


NUMpy errors

In [ ]:
import numpy as np

a,b = tuple(map(int,input().split()))

arr_a= np.empty((a,b),dtype=np.int)
arr_b = np.empty((a,b),dtype = np.int)
for i in range(a):
    arr_a[i] = (np.array(list(map(int,input().split()))))
for i in range(a):
    arr_b[i] = np.array(list(map(int,input().split())))

print(np.add(arr_a,arr_b))
print(np.subtract(arr_a,arr_b))
print(np.multiply(arr_a,arr_b))
print(np.floor_divide(arr_a,arr_b))
print(np.mod(arr_a,arr_b))
print(np.power(arr_a,arr_b))

Numpy Dot and Cross

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT


import numpy as np

a = int(input())
arr_a = np.empty((a,a),dtype=np.int)
arr_b = np.empty((a,a),dtype=np.int)

for i in range(a):
    arr_a[i] =  list(map(int,input().split()))
for i in range(a):
    arr_b[i] = list(map(int,input().split()))

o =  np.empty((a,a),dtype=np.int)
for i in range(a):
    for j in range(a):
        # print(arr_a[i][:],arr_b,arr_b[j][:],arr_b[:,j] )
        o[i,j] = np.dot((arr_a[i][:]),(arr_b[:,j]))

print(o)
print(np.dot(arr_a,arr_b))
print(np.cross(arr_a,arr_b))

Fibonacci


In [ ]:
cube = lambda x: x**3 # complete the lambda function

def fibonacci(n):
    # return a list of fibonacci numbers
    o =[]
    n1=0
    n2=1
    a = [n1,n2]
    if n==1:
        return [0]
    if n==0:
        return []
    for i in range(2,n):
        a.append(sum(a[-2:]))
    return a

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

In [ ]:
def fib(n):
  if n<=1:
    return n
  return fib(n-1) + fib(n-2)

for i in range(10):
  print(fib(i))

0
1
1
2
3
5
8
13
21
34


### palindrome

In [ ]:
str_1 = 'strmrts'
start =0
end = len(str_1) -1

for i in range(int(len(str_1)/2)):
  if str_1[start+i] != str_1[end-i]:
    print('not a palindrome')

### Reverse an Array best possible

In [ ]:
str_1 = 'nithin'
list_1 = list(str_1)
start =0
end = len(str_1) -1

for i in range(int(len(str_1)/2)):
  temp1  = str_1[end-i]
  temp2 = str_1[start+i]
  list_1[end-i] = temp2
  list_1[start+i] =  temp1

''.join(list_1)

'nihtin'

In [ ]:
for x in numbers:
    print("{:10.4f}".format(x))

In [ ]:
for i in enumerate(['R', 'a', 'n', 'k']):
  print(i)

(0, 'R')
(1, 'a')
(2, 'n')
(3, 'k')


In [ ]:
# Rotate an array

i = [1,2,3,4,5,6]

i.insert(0,[1,2])
print(i)
import numpy as np
a4 = np.array([[1,2,3,100],[4,5,6,200],[7,8,9,300],[10,11,12,13]])
a5 = np.array([[1,2,3,100,22],[4,5,6,200,33],[7,8,9,300,44],[10,11,12,13,55],[123,124,125,126,127]])
a4,a5

[[1, 2], 1, 2, 3, 4, 5, 6]


(array([[  1,   2,   3, 100],
        [  4,   5,   6, 200],
        [  7,   8,   9, 300],
        [ 10,  11,  12,  13]]),
 array([[  1,   2,   3, 100,  22],
        [  4,   5,   6, 200,  33],
        [  7,   8,   9, 300,  44],
        [ 10,  11,  12,  13,  55],
        [123, 124, 125, 126, 127]]))

In [ ]:
list_1 = []
a = a5
k = a5.shape[0]-1
list_1.extend(list(a[0,:]))
list_1.extend(list(a[1:,k]))
list_1.extend(list(a[k,:k])[::-1])
list_1.extend(list(a[1:k,0])[::-1])

print(list_1)
z = list_1[-1]
list_1.insert(0,z)
list_1.pop()
list_1

[1, 2, 5, 4]


[4, 1, 2, 5]

In [ ]:
a3 = np.array([[1,2,3,4,100],[5,6,7,8,200],[9,10,11,12,300],[13,14,15,16,400],[41,51,61,71,81]])
a3 =  np.array([[1,2,3,4,100,777],[5,6,7,8,200,888],[9,10,11,12,300,999],[13,14,15,16,400,111],[41,51,61,71,81,222],[41,51,61,71,81,222]])

k = a3.shape[0]-1
main_a = np.zeros((k+1,k+1),dtype = int)
a =a3
main_shape= a3.shape[0]
a_shape = k+1
list_o = []
for i in range(0,int(a_shape/2)):
    print(i)
    list_1 = []
    a = a3[0+i:main_shape-i,0+i:main_shape-i]
    # print(0+i,main_shape-i,0+i,main_shape-i)
    k = a.shape[0]-1
    main_a = np.zeros((k+1,k+1),dtype = int)
    a_shape = main_a.shape[0]
    print('a',a)
    k = a.shape[0] -1
    list_1.extend(list(a[0,:]))
    list_1.extend(list(a[1:,k]))
    list_1.extend(list(a[k,:k])[::-1])
    list_1.extend(list(a[1:k,0])[::-1])
    z = list_1[-1]
    list_1.insert(0,z)
    list_1.pop()

    for j in range(a_shape):
      main_a[0,j] = list_1[0]
      list_1.pop(0)

    for j in range(1,a_shape):

      main_a[j,a_shape-1] = list_1[0]
      list_1.pop(0)

    for k in range(a_shape-2,-1,-1):
      main_a[a_shape-1,k] = list_1[0]
      list_1.pop(0)

    for k in range(a_shape-2,0,-1):
      main_a[k,0] = list_1[0]
      list_1.pop(0)

    print('Done with round One')

    print(a3)
    # print('output \n',main_a)
    # print('start 2nd Round')
    list_o.append(main_a)

    print(list_o)

    if (main_shape%2) ==1:
      list_o[0][int(main_shape/2),int(main_shape/2)]  = a3[int(main_shape/2),int(main_shape/2)]

0
a [[  1   2   3   4 100 777]
 [  5   6   7   8 200 888]
 [  9  10  11  12 300 999]
 [ 13  14  15  16 400 111]
 [ 41  51  61  71  81 222]
 [ 41  51  61  71  81 222]]
Done with round One
[[  1   2   3   4 100 777]
 [  5   6   7   8 200 888]
 [  9  10  11  12 300 999]
 [ 13  14  15  16 400 111]
 [ 41  51  61  71  81 222]
 [ 41  51  61  71  81 222]]
[array([[  5,   1,   2,   3,   4, 100],
       [  9,   0,   0,   0,   0, 777],
       [ 13,   0,   0,   0,   0, 888],
       [ 41,   0,   0,   0,   0, 999],
       [ 41,   0,   0,   0,   0, 111],
       [ 51,  61,  71,  81, 222, 222]])]
1
a [[  6   7   8 200]
 [ 10  11  12 300]
 [ 14  15  16 400]
 [ 51  61  71  81]]
Done with round One
[[  1   2   3   4 100 777]
 [  5   6   7   8 200 888]
 [  9  10  11  12 300 999]
 [ 13  14  15  16 400 111]
 [ 41  51  61  71  81 222]
 [ 41  51  61  71  81 222]]
[array([[  5,   1,   2,   3,   4, 100],
       [  9,   0,   0,   0,   0, 777],
       [ 13,   0,   0,   0,   0, 888],
       [ 41,   0,   0,   0,   0

In [ ]:
list_o[0][1:4,1:4] = list_o[1]

In [ ]:
a3,list_o[0]

(array([[  1,   2,   3,   4, 100],
        [  5,   6,   7,   8, 200],
        [  9,  10,  11,  12, 300],
        [ 13,  14,  15,  16, 400],
        [ 41,  51,  61,  71,  81]]),
 array([[  5,   1,   2,   3,   4],
        [  9,  10,   6,   7, 100],
        [ 13,  14,   0,   8, 200],
        [ 41,  15,  16,  12, 300],
        [ 51,  61,  71,  81, 400]]))

# geekForGeeks

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
n = 10
for i in range(n):
    # pass can be used as placeholder
    # when code is to added later
    pass

In [ ]:
a,b  =4,0
try:
  k = a//b
  print(k)
except ZeroDivisionError:
  print('Division By zero')
finally:
  print('This is always executed')

Division By zero
This is always executed


In [ ]:
# lambda Functions
cube = lambda x: x**3 # complete the lambda function
print(cube(2))
sum_1 = lambda x:x+4

8


In [ ]:
# Yield Keyword
def fun():
      # Yield the value 1, pausing the function here
    yield 1
    # Yield the value 2, pausing the function again
    yield 2
    # Yield the value 3, pausing the function once more
    yield 3
# Iterate through the values yielded by the function
for value in fun():
    print(value)

1
2
3


In [ ]:
# Lambda Function Here
g = lambda x: x*x
g(8)
a,b = 'nithin', 28
print('My name is ',a,'\n My age is ',b,end = '**')
print('\n My name is {} and my age is {}'.format(a,b))
print('\n My name is {} and my age is {:7.4f}'.format(a,b))
print(f'My name is \' {a}\' and my age is {b}')
print(f'My name is \'{a}\' and my age is \'{b}\'')
print(f'My name is {a} and my age is {b}')
print("My name is %s and My age is %d" % (a,b))
print("My name is %s and My age is %5.4f" % (a,b))
print("My name is %s and My age is %1.2f" % (a,b))

My name is  nithin 
 My age is  28**
 My name is nithin and my age is 28

 My name is nithin and my age is 28.0000
My name is ' nithin' and my age is 28
My name is 'nithin' and my age is '28'
My name is nithin and my age is 28
My name is nithin and My age is 28
My name is nithin and My age is 28.0000
My name is nithin and My age is 28.00


In [ ]:
import random
print(random.randint(1,100))
print(round(random.uniform(1,10),4))

44
9.9118


In [ ]:
# lists are mutable
# Tuples are immutable
a = []
a.append(10)
a.insert(1,20)
a.extend([30,21])
print(a)
a.remove(20) # Remove the First occuring value
a.pop(2) # pop Out based on the index for lists but removes last element for Set
print(a)

[10, 20, 30, 21]
[10, 30]


# GeekForGeeks

In [ ]:
a = [1,323,4,5,644,0]
max = -1000000

for i in a:
  if i >max:
    max =i
print(max)

644


Factorial

In [ ]:
def factorial(n):
  return 1 if (n==1) or (n==0) else n*factorial(n-1)

factorial(10)

3628800

Prime Number

In [ ]:
n =int(input())
k= []
for i in range(1,n):
  if i==1:
    k.append(i)
  else:
    for j in range(2,i):
      if i%j==0:
        break
    else:
      k.append(i)

print(set(k))

20
{1, 2, 3, 5, 7, 11, 13, 17, 19}


In [ ]:
# AScii Value
print(ord('c'))

99


In [ ]:
# Array Rotation
a = [1,2,3,4,5]
for i in range(3):
  a.append(a.pop(0))
  print(a)
print(a,a[::-1],a[1:],a[1::])

[2, 3, 4, 5, 1]
[3, 4, 5, 1, 2]
[4, 5, 1, 2, 3]
[4, 5, 1, 2, 3] [3, 2, 1, 5, 4]


In [ ]:
# Array  Swap
a = [1,2,3,4,5]
temp1 = a[4]
a[4] = a[2]
a[2] = temp1
print(sum(a),a,a.clear())

15 [] None


In [ ]:
# reduce usage -  multiply all the elements in the Iterable
from functools import reduce
from operator import mul
a = [1,2,3,4,5]
reduce(mul,a)

120

In [ ]:
# Cumulative Sum
a = [1,2,3,4,5]
list_1 = []
j= 0
for i in a:
  j= j + i
  list_1.append(j)
print(list_1)

[1, 3, 6, 10, 15]


In [ ]:
list_1 = [1,2,3,4]
list_1.remove(1)

[2, 3, 4]

In [ ]:
def twoSum( nums, target):
    output = []
    output2 = []
    for i in range(len(nums)):
        if nums[i] <= target:
            k  = target-nums[i]
            if (k in nums):
                if (i!=nums.index(k)):
                    output.append(i)
                    output.append(nums.index(k))

    return output[:2]
nums = [-1,-2,-3,-4,-5]
twoSum(nums, target = -8)

[]

In [ ]:
list_1 = [1,2,3]
list_2 = [3,4,5]

[1, 2, 3, 3, 4, 5]

In [ ]:
# Hour Glass

#!/bin/python3

import math
import os
import random
import re
import sys


def hourglassSum(arr):
    # Write your code here
    output = []
    for i in range(len(arr) - 2):
        for j in range(len(arr) - 2):
            output.append(sum(arr[i][j:j+3]) + (arr[i+1][j:j+3][1]) + sum(arr[i+2][j:j+3]))

    return max(output)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()


### Recursion

In [9]:
def print1(a):
  if a > 10:
    return
  else:

    a+=1
  print1(a)
  print(a)

print1(4)

In [12]:
def printname(i,n):
  if i>n:
    return
  else:
    i+=1
  printname(i,n)
  print('Nithin',i)
printname(1,5)

Nithin 6
Nithin 5
Nithin 4
Nithin 3
Nithin 2


In [22]:
def reverserecursion(l,r,a):
  if l>=r:
    return
  else:
    a[l],a[r] = a[r], a[l]
  reverserecursion(l+1,r-1,a)
  print(a)

reverserecursion(0,5,[1,5,32,7,3,8])

[8, 3, 7, 32, 5, 1]
[8, 3, 7, 32, 5, 1]
[8, 3, 7, 32, 5, 1]


In [29]:
def reverserecursion(l,r,a):
  if l>=r:
    return
  elif a[l] != a[r]:
    return False
  else:
    reverserecursion(l+1,r-1,a)

reverserecursion(0,5,'MADAM1')

False

In [15]:
def factorial(n):
  if n==1:
    return 1
  else:
    return n* factorial(n-1)
factorial(5)

120

In [ ]:

def printN(i,num):
  if i <num:
    print(i,'nithin')
  else:
    return
  i= i+1
  printN(i,num)

printN(0,5)

0 nithin
1 nithin
2 nithin
3 nithin
4 nithin


In [ ]:
def printN(i,num):
  if num>0:
    print(i,'nithin',num)
  else:
    return
  num = num-1
  printN(i,num)

printN(0,5)

0 nithin 5
0 nithin 4
0 nithin 3
0 nithin 2
0 nithin 1


In [ ]:
def sumN(i,num,sum):
  if num ==1:
    print(num)
    print(sum)
    return sum
  num = num-1
  sum = num +sum
  print(num,sum)
  sumN(i,num,sum=sum)

In [ ]:
a = sumN(0,5,sum=0)

4 4
3 7
2 9
1 10
1
10
