<a href="https://colab.research.google.com/github/nithin-k-mundrathi/python_practice/blob/main/Python_New_Programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
s = "India"
s[::-1]
len(s)

5

In [ ]:
import sys

-sys.maxsize -1

-9223372036854775808

In [ ]:
a = [1,75,6,2,3]

In [ ]:
round(1.1234,1)

1.1

### MAx Continous Sub Array of of length =k

In [ ]:
int_min = -sys.maxsize-1

for i in range(len(a)-2-1):
  max_sum = 0
  for j in range(2):
    max_sum = max_sum + a[i+j]

  int_min = max(int_min,max_sum)

In [ ]:
int_min

81

### PRime _Number


In [ ]:
n = 21
for i in range(2,int(n/2)+1):
  if n%i==0:
    print(False)
    break
  else:
    print(True)

True
False


In [ ]:
def prime_N(n):

  for i in range(n):

    for j in range(2, int(i/2)+1):
      if i%j==0:
        break
      print(i)

### GCD


In [ ]:
def gcd(a,b):

  if b==0:
    return a
  else:
    return gcd(b,a%b)

In [ ]:
gcd(16,4)

4

In [ ]:
a = [1,2,3,4,5]
b = [5,2,7,9]

list(set(a) & set(b))

[2, 5]

  ### Join all elements in a list

In [ ]:
    k = ''.join([str(i) for i in range(1,n+1)])
    print(k)

In [ ]:
arr  = list(map(int, input().split()))
k=-1000
print(arr)
for i in arr:
    if i >= k:
        k=i
print(k)
z = []
for p in arr:
    if p !=k:
        z.append(p)

print(max(z))

6 6 6 6 6 6 6 6 6 5
[6, 6, 6, 6, 6, 6, 6, 6, 6, 5]
6
5


%md Second largest

In [ ]:

    n1 =n2 =1000000

    for i in list_scores:

        if i < n1:
            n2 = n1
            n1 = i

        elif i<n2 and i!=n1:
            n2 = i
    a = []
    for j in list_o:
        if j[1] == n2:
            a.append(j[0])

List comprehensions


In [ ]:
    list_1 = [i for i in range(x+1)]
    list_2 = [i for i in range(y+1)]
    list_3 = [i for i in range(z+1)]


    p = [[i,j,k] for i in list_1 for j in list_2 for k in list_3 if i+j+k !=n]


    print(p)

List comprehension with if and else

In [ ]:
def swap_case(s):
    list_s = s.split(' ')
    k =[]
    for i in list_s:
        # if else comes first in list comprehension
        k.append(''.join(
            [j.lower() if j.isupper() else j.upper() for j in list(i) ]))
    return ' '.join(k)

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

Avg using a Dict upto 2 decimal places

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

    print(
        '{:.2f}'.format(sum(student_marks[query_name][:])/len(student_marks[query_name]))
        )

  # give : when formatting to decide as number and just {} as a string
  output = "Hello {.3f} {}! You just delved into python.".format(10,last)
  print(output)

In [ ]:
print('{:.4f}'.format(7)),print('{:.4f}'.format(70)),print('{:.4f}'.format(10))

7.0000
70.0000
10.0000


(None, None, None)

In [ ]:
list_1 = [1,23,4]

list_1[2] = list_1[2] - 1
list_1

[1, 23, 3]

Collectioons Counter

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import Counter
number_of_shoes = input()
shoe_size  = list(map(int,input().split()))
shoe_size_counter = Counter(shoe_size)
n_customers = input()
c_shoes = []

for i in range(int(n_customers)):
    c_shoes.append(list(map(int,input().split())))

sum_a = 0
for i in range(len(c_shoes)):
    if (c_shoes[i][0] in shoe_size_counter.keys()) & (shoe_size_counter[c_shoes[i][0]]>0):
        shoe_size_counter[c_shoes[i][0]] = shoe_size_counter[c_shoes[i][0]] -1
        sum_a =sum_a + c_shoes[i][1]

print(sum_a)

permutations

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from itertools import permutations
a,b = input().split()

o =list(permutations(list(a),int(b)))
collect_o = []
for i in o:
    k = i
    collect_o.append(''.join(k))

for i in sorted(collect_o):
    print(i)

Text cell


In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

a = input()
a1 = set(list(map(int,input().split())))
b = input()
b1 = set(list((map(int, input().split()))))
difference = set(a1).intersection(set(b1))

k1 = a1
k2 = b1
for i in list(difference):
    k1.discard(i)

    k2.discard(i)

for i in sorted(list(k1.union(k2))):
    print(i)

Lists

In [ ]:
if __name__ == '__main__':
    N = int(input())
    list_1 = []
    for i in range(N):
        a  = input().split()
        if a[0]=='insert':
            list_1.insert(int(a[1]),int(a[2]))
        if a[0]=='print':
            print(list_1)
        if a[0] == 'remove':
            list_1.remove(int(a[1]))
        if a[0] == 'append':
            list_1.append(int(a[1]))
        if a[0] == 'pop':
            list_1.pop()
        if a[0] == 'reverse':
            list_1.reverse()
        if a[0] == 'sort':
            list_1.sort()


In [ ]:
pos = [1,2,3,4]
pos[::-1]

[4, 3, 2, 1]

Numpy


In [ ]:
import numpy as np
np.set_printoptions(legacy = '1.13')

a,b  = tuple(map(int,input().split()))

# print(np.identity(a))

print(np.eye(a,b,k=0))

5


ValueError: not enough values to unpack (expected 2, got 1)

NUMpy errors

In [ ]:
import numpy as np

a,b = tuple(map(int,input().split()))

arr_a= np.empty((a,b),dtype=np.int)
arr_b = np.empty((a,b),dtype = np.int)
for i in range(a):
    arr_a[i] = (np.array(list(map(int,input().split()))))
for i in range(a):
    arr_b[i] = np.array(list(map(int,input().split())))

print(np.add(arr_a,arr_b))
print(np.subtract(arr_a,arr_b))
print(np.multiply(arr_a,arr_b))
print(np.floor_divide(arr_a,arr_b))
print(np.mod(arr_a,arr_b))
print(np.power(arr_a,arr_b))

Numpy Dot and Cross

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT


import numpy as np

a = int(input())
arr_a = np.empty((a,a),dtype=np.int)
arr_b = np.empty((a,a),dtype=np.int)

for i in range(a):
    arr_a[i] =  list(map(int,input().split()))
for i in range(a):
    arr_b[i] = list(map(int,input().split()))

o =  np.empty((a,a),dtype=np.int)
for i in range(a):
    for j in range(a):
        # print(arr_a[i][:],arr_b,arr_b[j][:],arr_b[:,j] )
        o[i,j] = np.dot((arr_a[i][:]),(arr_b[:,j]))

print(o)
print(np.dot(arr_a,arr_b))
print(np.cross(arr_a,arr_b))

Fibonacci


In [ ]:
cube = lambda x: x**3 # complete the lambda function

def fibonacci(n):
    # return a list of fibonacci numbers
    o =[]
    n1=0
    n2=1
    a = [n1,n2]
    if n==1:
        return [0]
    if n==0:
        return []
    for i in range(2,n):
        a.append(sum(a[-2:]))
    return a

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

In [ ]:
for x in numbers:
    print("{:10.4f}".format(x))

Pattern Coding

In [ ]:
k = int(input())
for i in range(1,k):
  z = []
  for i in range(k):
    z.append('*')
  print(''.join(z),end='')
  print()

5
*****
*****
*****
*****


In [ ]:
# Empty Square
k  =int(input())
for i in range(k):
  z = []
  for j in range(k):
    if i==0 or i==(k-1) or j==0 or j==(k-1):
      z.append('*')
    else:
      z.append(' ')
  print(''.join(z),end='')
  print('\n',end='')

4
****
*  *
*  *
****


In [ ]:
# left triangle
k = int(input())
for i in range(k):
  z = []
  for j in range(k):
    if j<=i:
      z.append('*')
    else:
      z.append(' ')
  print(''.join(z),end='')
  print('\n',end='')


5
*    
**   
***  
**** 
*****


In [ ]:
#right Triangle
k = int(input())
for i in range(k-1,-1,-1):
  z = []
  for j in range(0,k):
    if j<i:
      z.append(' ')
    else:
      z.append('*')

  print(''.join(z),end='')
  print('\n',end='')


5
    *
   **
  ***
 ****
*****


In [ ]:
#Left dOWN Triangle
k = int(input())
for i in range(k):
  z = []
  for j in range(k,0,-1):
    if j>i:
      z.append('*')
    else:
      z.append(' ')
  print(''.join(z),end='')
  print('\n',end='')


5
*****
**** 
***  
**   
*    


In [ ]:
#Left dOWN Triangle
k = int(input())
for i in range(k):
  z = []
  for j in range(k-1,-1,-1):
    if j<i:
      z.append(' ')
    else:
      z.append('*')
  p = z[::-1]

  print(''.join(p),end='')
  print('\n',end='')

#   #Left dOWN Triangle
# k = int(input())
# for i in range(k-1,-1,-1):
#   z = []
#   for j in range(k-1,-1,-1):
#     if i>=j:
#       z.append('*')
#     else:
#       z.append(' ')
#   print(''.join(z),end='')
#   print('\n',end='')

5
*****
 ****
  ***
   **
    *


In [ ]:
#Hollow  Triangle
k = int(input())
for i in range(k):
  z = []
  for j in range(0,k):
    if (i==k-1):
        z.append('*')
    elif (i==j) or (j<=0):
      z.append('*')
    else:
      z.append(' ')

  print(''.join(z),end='')
  print('\n',end='')

6
*     
**    
* *   
*  *  
*   * 
******


In [ ]:
# Pyramid
k = int(input())
for i in range(int(k)):
  z = []
  for j in range(0,k):
    if int(k/2)-i <=j <= int(k/2)+i:
        z.append('*')
    else:
      z.append(' ')
  if i> int(k/2):
    break

  print(''.join(z),end='')
  print('\n',end='')

9
    *    
   ***   
  *****  
 ******* 
*********


In [ ]:
# Hollow Pyramid
k = int(input())
for i in range(int(k)):
  z = []
  for j in range(0,k):
    if int(k/2)-i <=j <= int(k/2)+i:
      if ( (int(k/2)-i) < j < (int(k/2)+i) ):
        z.append(' ')
      else:
        z.append('*')
    else:
      z.append(' ')
  if i> int(k/2):
    break

  print(''.join(z),end='')
  print('\n',end='')

17
        *        
       * *       
      *   *      
     *     *     
    *       *    
   *         *   
  *           *  
 *             * 
*               *


In [ ]:
# Pyramid
k = int(input())
for i in range(int(k),-1,-1):
  if i> int(k/2):
    continue
  else:
    z = []
    for j in range(0,k):
      if int(k/2)-i <=j <= int(k/2)+i:
          z.append('*')
      else:
        z.append(' ')

  print(''.join(z),end='')
  print('\n',end='')

11
***********
 ********* 
  *******  
   *****   
    ***    
     *     


In [ ]:
# Diamond
k = int(input())

for i in range(k):
  z = []
  if i <= int(k/2):
    for j in range(k):
      if int(k/2)-i <=j <= int(k/2)+i:
          z.append('*')
      else:
          z.append(' ')
  if i > int(k/2):
    for j in range(k):
      if (i-int(k/2))<=j<= int(k)-1-(i-int(k/2)):
        z.append('*')
      else:
        z.append(' ')
  print(''.join(z),end='')
  print('\n',end='')

13
      *      
     ***     
    *****    
   *******   
  *********  
 *********** 
*************
 *********** 
  *********  
   *******   
    *****    
     ***     
      *      


In [ ]:
for i in enumerate(['R', 'a', 'n', 'k']):
  print(i)

(0, 'R')
(1, 'a')
(2, 'n')
(3, 'k')


In [ ]:
# hollow Diamond
k = int(input())

for i in range(k):
  z = []
  if i < int(k/2):
    for j in range(k):
      if int(k/2)-i <=j <= int(k/2)+i:
        if int(k/2)-i < j < int(k/2)+i:
          z.append(' ')
        else:
          z.append('*')
      else:
        z.append(' ')
  if i== int(k/2):
    for j in range(k):
      z.append('*')
  if i > int(k/2):
    for j in range(k):
      if (i-int(k/2))<=j<= int(k)-1-(i-int(k/2)):
        if (i-int(k/2))< j< int(k)-1-(i-int(k/2)):
          z.append(' ')
        else:
          z.append('*')
      else:
        z.append(' ')

  print(''.join(z),end='')
  print('\n',end='')

9
    *    
   * *   
  *   *  
 *     * 
*********
 *     * 
  *   *  
   * *   
    *    


In [ ]:
# HourGlass Diamond
k = int(input())

for i in range(k):
  z = []
  if i <= int(k/2):
    for j in range(k-1,-1,-1):
      if i <=j <= int(k)-1-i:
        z.append('*')
      else:
        z.append(' ')
  if i > int(k/2):
    for j in range(0,k):
      if (int(k)-1-int(i))<= j <= int(i):
        z.append('*')
      else:
        z.append(' ')

  print(''.join(z),end='')
  print('\n',end='')

11
***********
 ********* 
  *******  
   *****   
    ***    
     *     
    ***    
   *****   
  *******  
 ********* 
***********


In [ ]:
# right Pascal
k = int(input())

for i in range(1,k+1):
  z = []
  if i <= int(k/2) +1:
    for j in range(1,k):
      if j <=i:
        z.append('*')
      else:
        z.append(' ')
  else:
      for j in range(1,k+1):
        if j < int(k) - int(i)+1:
          z.append('*')
        else:
          z.append(' ')

  print(''.join(z),end='')
  print('\n',end='')

9
*       
**      
***     
****    
*****   
***      
**       
*        
         


In [ ]:
# Left Pascal
k = int(input())

for i in range(0,2*k):
  z = []
  if i < int(k):
    for j in range(0,k):
      if j <int(k)-i-1:
        z.append(' ')
      else:
        z.append('*')
  else:
      for j in range(0,k):
        if j > i-k:
          z.append('*')
        else:
          z.append(' ')

  print(''.join(z),end='')
  print('\n',end='')

5
    *
   **
  ***
 ****
*****
 ****
  ***
   **
    *
     


In [ ]:
# Plus
k = int(input())

for i in range(k):
  z = []
  if i != int(k/2):
    for j in range(k):
      if j == int(k/2):
        z.append('*')
      else:
        z.append(' ')
  else:
      for j in range(k):
        z.append('*')

  print(''.join(z),end='')
  print('\n',end='')

11
     *     
     *     
     *     
     *     
     *     
***********
     *     
     *     
     *     
     *     
     *     


In [ ]:
# Cross Pattern
k = int(input())

for i in range(k):
  z = []
  if i <= int(k):
    for j in range(k):
      if (j==i) or (j ==int(k-1-i)):
        z.append('*')
      else:
        z.append(' ')
  else:
      for j in range(k):
        z.append('*')

  print(''.join(z),end='')
  print('\n',end='')

11
*         *
 *       * 
  *     *  
   *   *   
    * *    
     *     
    * *    
   *   *   
  *     *  
 *       * 
*         *


In [ ]:
# Rotate an array

i = [1,2,3,4,5,6]

i.insert(0,[1,2])
print(i)
import numpy as np
a4 = np.array([[1,2,3,100],[4,5,6,200],[7,8,9,300],[10,11,12,13]])
a5 = np.array([[1,2,3,100,22],[4,5,6,200,33],[7,8,9,300,44],[10,11,12,13,55],[123,124,125,126,127]])
a4,a5

[[1, 2], 1, 2, 3, 4, 5, 6]


(array([[  1,   2,   3, 100],
        [  4,   5,   6, 200],
        [  7,   8,   9, 300],
        [ 10,  11,  12,  13]]),
 array([[  1,   2,   3, 100,  22],
        [  4,   5,   6, 200,  33],
        [  7,   8,   9, 300,  44],
        [ 10,  11,  12,  13,  55],
        [123, 124, 125, 126, 127]]))

In [ ]:
list_1 = []
a = a5
k = a5.shape[0]-1
list_1.extend(list(a[0,:]))
list_1.extend(list(a[1:,k]))
list_1.extend(list(a[k,:k])[::-1])
list_1.extend(list(a[1:k,0])[::-1])

print(list_1)
z = list_1[-1]
list_1.insert(0,z)
list_1.pop()
list_1

[1, 2, 5, 4]


[4, 1, 2, 5]

In [ ]:
a3 = np.array([[1,2,3,4,100],[5,6,7,8,200],[9,10,11,12,300],[13,14,15,16,400],[41,51,61,71,81]])
a3 =  np.array([[1,2,3,4,100,777],[5,6,7,8,200,888],[9,10,11,12,300,999],[13,14,15,16,400,111],[41,51,61,71,81,222],[41,51,61,71,81,222]])

k = a3.shape[0]-1
main_a = np.zeros((k+1,k+1),dtype = int)
a =a3
main_shape= a3.shape[0]
a_shape = k+1
list_o = []
for i in range(0,int(a_shape/2)):
    print(i)
    list_1 = []
    a = a3[0+i:main_shape-i,0+i:main_shape-i]
    # print(0+i,main_shape-i,0+i,main_shape-i)
    k = a.shape[0]-1
    main_a = np.zeros((k+1,k+1),dtype = int)
    a_shape = main_a.shape[0]
    print('a',a)
    k = a.shape[0] -1
    list_1.extend(list(a[0,:]))
    list_1.extend(list(a[1:,k]))
    list_1.extend(list(a[k,:k])[::-1])
    list_1.extend(list(a[1:k,0])[::-1])
    z = list_1[-1]
    list_1.insert(0,z)
    list_1.pop()

    for j in range(a_shape):
      main_a[0,j] = list_1[0]
      list_1.pop(0)

    for j in range(1,a_shape):

      main_a[j,a_shape-1] = list_1[0]
      list_1.pop(0)

    for k in range(a_shape-2,-1,-1):
      main_a[a_shape-1,k] = list_1[0]
      list_1.pop(0)

    for k in range(a_shape-2,0,-1):
      main_a[k,0] = list_1[0]
      list_1.pop(0)

    print('Done with round One')

    print(a3)
    # print('output \n',main_a)
    # print('start 2nd Round')
    list_o.append(main_a)

    print(list_o)

    if (main_shape%2) ==1:
      list_o[0][int(main_shape/2),int(main_shape/2)]  = a3[int(main_shape/2),int(main_shape/2)]

0
a [[  1   2   3   4 100 777]
 [  5   6   7   8 200 888]
 [  9  10  11  12 300 999]
 [ 13  14  15  16 400 111]
 [ 41  51  61  71  81 222]
 [ 41  51  61  71  81 222]]
Done with round One
[[  1   2   3   4 100 777]
 [  5   6   7   8 200 888]
 [  9  10  11  12 300 999]
 [ 13  14  15  16 400 111]
 [ 41  51  61  71  81 222]
 [ 41  51  61  71  81 222]]
[array([[  5,   1,   2,   3,   4, 100],
       [  9,   0,   0,   0,   0, 777],
       [ 13,   0,   0,   0,   0, 888],
       [ 41,   0,   0,   0,   0, 999],
       [ 41,   0,   0,   0,   0, 111],
       [ 51,  61,  71,  81, 222, 222]])]
1
a [[  6   7   8 200]
 [ 10  11  12 300]
 [ 14  15  16 400]
 [ 51  61  71  81]]
Done with round One
[[  1   2   3   4 100 777]
 [  5   6   7   8 200 888]
 [  9  10  11  12 300 999]
 [ 13  14  15  16 400 111]
 [ 41  51  61  71  81 222]
 [ 41  51  61  71  81 222]]
[array([[  5,   1,   2,   3,   4, 100],
       [  9,   0,   0,   0,   0, 777],
       [ 13,   0,   0,   0,   0, 888],
       [ 41,   0,   0,   0,   0

In [ ]:
list_o[0][1:4,1:4] = list_o[1]

In [ ]:
a3,list_o[0]

(array([[  1,   2,   3,   4, 100],
        [  5,   6,   7,   8, 200],
        [  9,  10,  11,  12, 300],
        [ 13,  14,  15,  16, 400],
        [ 41,  51,  61,  71,  81]]),
 array([[  5,   1,   2,   3,   4],
        [  9,  10,   6,   7, 100],
        [ 13,  14,   0,   8, 200],
        [ 41,  15,  16,  12, 300],
        [ 51,  61,  71,  81, 400]]))

# geekForGeeks

In [3]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [4]:
n = 10
for i in range(n):
    # pass can be used as placeholder
    # when code is to added later
    pass

In [7]:
a,b  =4,0
try:
  k = a//b
  print(k)
except ZeroDivisionError:
  print('Division By zero')
finally:
  print('This is always executed')

Division By zero
This is always executed


In [8]:
# Yield Keyword
def fun():
      # Yield the value 1, pausing the function here
    yield 1
    # Yield the value 2, pausing the function again
    yield 2
    # Yield the value 3, pausing the function once more
    yield 3
# Iterate through the values yielded by the function
for value in fun():
    print(value)

1
2
3


In [34]:
# Lambda Function Here
g = lambda x: x*x
g(8)
a,b = 'nithin', 28
print('My name is ',a,'\n My age is ',b,end = '**')
print('\n My name is {} and my age is {}'.format(a,b))
print('\n My name is {} and my age is {:7.4f}'.format(a,b))
print(f'My name is \' {a}\' and my age is {b}')
print(f'My name is \'{a}\' and my age is \'{b}\'')
print(f'My name is {a} and my age is {b}')
print("My name is %s and My age is %d" % (a,b))
print("My name is %s and My age is %5.4f" % (a,b))
print("My name is %s and My age is %1.2f" % (a,b))

My name is  nithin 
 My age is  28**
 My name is nithin and my age is 28

 My name is nithin and my age is 28.0000
My name is ' nithin' and my age is 28
My name is 'nithin' and my age is '28'
My name is nithin and my age is 28
My name is nithin and My age is 28
My name is nithin and My age is 28.0000
My name is nithin and My age is 28.00


In [37]:
import random
print(random.randint(1,100))
print(round(random.uniform(1,10),4))

44
9.9118


In [39]:
# lists are mutable
# Tuples are immutable
a = []
a.append(10)
a.insert(1,20)
a.extend([30,21])
print(a)
a.remove(20) # Remove the First occuring value
a.pop(2) # pop Out based on the index for lists but removes last element for Set
print(a)

[10, 20, 30, 21]
[10, 30]
